AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-burger

  Sample SAM Template for api-burger

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON
    Runtime: nodejs20.x
    Environment:
      Variables:
        DATABASE_URL: postgresql://postgres:123456789@burger-db.ctc26gwyiewv.sa-east-1.rds.amazonaws.com:5432/burger_db

Resources:
  GetStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.getStockHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        GetStock:
          Type: Api
          Properties:
            Path: /stock
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
        Loader:
          - .prisma=file
          - .so.node=file
        AssetNames: '[name]'

  
  AddItemToStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.addItemToStockHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        GetStock:
          Type: Api
          Properties:
            Path: /stock
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
        Loader:
          - .prisma=file
          - .so.node=file
        AssetNames: '[name]'
  
  DeleteItemFromStockFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.deleteItemFromStockHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        GetStock:
          Type: Api
          Properties:
            Path: /stock/{id}
            Method: delete
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
        Loader:
          - .prisma=file
          - .so.node=file
        AssetNames: '[name]'
    
  UpdateStockQuantityFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.updateStockQuantityHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        GetStock:
          Type: Api
          Properties:
            Path: /stock/update
            Method: put
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
          - app.ts
        Loader:
          - .prisma=file
          - .so.node=file
        AssetNames: '[name]'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
